#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov  1 12:21:54 2022

@author: apple


Problem Statement : Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""
a,b,c,add,n = 1,1,0,0,0
while n <= 4000000:
    c = a+b
    a = b
    b = c
    if c%2 == 0:add += c
    n = c
print(add)    
    
    
